### ISSUE TITLE
duplicate eslint dependency

### ISSUE THREAD

**Issue by bluelhf** [Testausserveri/matikkaeditori.fi-v3#40]
package.json has two different eslint versions, one for dev and one for production — is this intended?

https://github.com/Testausserveri/matikkaeditori.fi-v3/blob/21f6b8a407c8a3fd2ac6c746cdb482258f9e583f/package.json#L28
https://github.com/Testausserveri/matikkaeditori.fi-v3/blob/21f6b8a407c8a3fd2ac6c746cdb482258f9e583f/package.json#L97

p.s. i'm not used to the javascript ecosystem, so i'm not sure how you're supposed to resolve this kind of thing. looks like you'd probably want to get rid of the development dependency...

**Comment by Esinko** [comment]
This is most likely a mistake I made while doing major package upgrades a while back.
If you want to fix this, remove the eslint depenency (keep the dev one) and try to start the development version, so we can be sure the real dependency has no effect on the build process.
