### ISSUE TITLE
Add project licence

### ISSUE THREAD

**Issue by bluelhf** [Testausserveri/matikkaeditori.fi-v3#44]
Matikkaeditori should contain a licence to qualify as open-source software. The copy-left requirements of our dependencies should be evaluated, and a corresponding LICENCE file should be added. I suspect we'll need GPL v3 to adhere with restrictions placed by dependencies.

P.S. Licence is indeed the correct spelling for the noun in most English-speaking countries. I suggest we it in place of license — GitHub recognises both.
![image](https://user-images.githubusercontent.com/52505120/202129724-bee68e61-78ce-490e-8385-2adea923a437.png)

**Comment by Esinko** [comment]
I'll just add the `GPL v3` license for now.
