### ISSUE TITLE
Weird "hello" in mobile toolbar

### ISSUE THREAD

**Issue by bluelhf** [Testausserveri/matikkaeditori.fi-v3#49]
![image](https://user-images.githubusercontent.com/52505120/214779308-97915945-ad3e-4756-b57c-01873b016b71.png)
what :D

**Comment by ahnl** [comment]
Siihen pitäisi tulla mobiiliversion kaavanappulat, jos oikein muistan. Se oli vaan jäänyt kesken, eikä sitä koskaan implementoitu loppuun.On 26. Jan 2023, at 9.24, Ilari Suhonen ***@***.***> wrote:﻿

what :D

**Comment by Esinko** [comment]
This has been fixed with a placeholder for now.
